### ISSUE TITLE
ci: test suite failures — 2026-06-24

### ISSUE THREAD

**Issue by Pavua** [Pavua/Krab-Ear#1797]
## Python — chunk-timeout hangs (order-dependent)

Tests pass in isolation but hang during full suite chunk run (pytest-timeout kills at 30s).

**Observed hung tests (different each run):**
- `test_stt_router.py::test_audio_lid_detection_returns_detected_lang`
- `test_observability.py` (stuck in `state_store._append_ndjson_raw` file open)
- `core/engine.py:warmup` path (third run)

**Root cause pattern (from CLAUDE.md):** BackendService daemon threads (DiskSpaceMonitor, RecapScheduler, ExportScheduler) not stopped in tearDown → `threading._shutdown()` hangs at chunk exit → pytest-timeout kills individual test mid-run.

**Fix**: verify all test classes instantiating `BackendService` call `self.service.close()` in `tearDown` (PR #1782 pattern).

---

## Swift — BackendToastShowTests timing failure

**1 failure out of 1088 tests:**

```
BackendToastShowTests.swift:187: error:
-[KrabEarAgentTests.BackendToastShowTests test_panel_hidden_after_fade]
XCTAssertEqual failed: ("Optional(true)") is not equal to ("Optional(false)")
Panel should be hidden after duration + fade animation
(0.873 seconds)
```

**Root cause**: timing-sensitive assertion checking fade animation completion. Panel still visible when assertion runs. Add a small wait or use XCTKVOExpectation instead of fixed delay.

---

*Auto-generated by scheduled CI health check — 2026-06-24*

**Comment by Pavua** [comment]
Дубликат ежедневного scheduled-task `krab-ear-test-health`.

Хронический локальный hang полного pytest tracked в #1909.
Последний осмысленный ubuntu-сигнал — #1919 (2026-08-13).

Закрыто волной W1 (2026-08-16). Генератор больше не должен открывать
`ci: test suite failure — DATE` на тот же hang.
