### ISSUE TITLE
ci: Swift test flake — InlineTranslationCacheTests (NSCache eviction under memory pressure) — 2026-06-20

### ISSUE THREAD

**Issue by Pavua** [Pavua/Krab-Ear#1783]
## Failing test

`InlineTranslationCacheTests.test_cacheHit_afterStore_returnsTrue`
File: `Tests/KrabEarAgentTests/InlineTranslationCacheTests.swift:36`

## Failure output

```
/Users/pablito/Antigravity_AGENTS/Krab Ear/native/KrabEarAgent/Tests/KrabEarAgentTests/InlineTranslationCacheTests.swift:36: error: -[KrabEarAgentTests.InlineTranslationCacheTests test_cacheHit_afterStore_returnsTrue] : XCTAssertTrue failed - Должен быть cache hit после сохранения
Test Case '-[KrabEarAgentTests.InlineTranslationCacheTests test_cacheHit_afterStore_returnsTrue]' failed (0.033 seconds)
Test Suite 'InlineTranslationCacheTests' failed at 2026-06-20 14:08:49.835.
  Executed 1072 tests, with 5 tests skipped and 1 failure (0 unexpected) in 53.323 (53.405) seconds
```

## Root cause

`NSCache` evicts objects under system memory pressure. During the full 1072-test suite run there is enough memory pressure that the freshly-stored object gets evicted before `inlineTranslationCacheHit` reads it.

The test **passes in isolation** (`swift test --filter InlineTranslationCacheTests` → all 7 tests green).

## Fix

Replace `NSCache` in the test with a plain `[String: String]` dictionary (since tests don't need LRU eviction semantics), or use `cache.countLimit = 0` / `cache.totalCostLimit = 0` to prevent eviction during tests.

## Suite status (2026-06-20)

- **Python**: ✅ All tests passed (exit code 0, ~6500+ tests)
- **Swift**: ⚠️ 1071/1072 passed, 5 skipped, 1 flaky failure (this issue)
